#################################################################################
# Файл используется при фетчинге схемы бэкенда и объединяется с основной схемой #
#################################################################################

directive @client on FIELD

extend type UserCurrentResponse {
    """Роль пользователя. Использовать, только если в запросе присутствует roles."""
    role: UserRoleEnum!
}

extend type UserEntity {
    """Инициалы. Использовать только если в запросе присутствуют поля паспорта студента или поля сотрудника."""
    initials: String!
    """Полное имя. Использовать только если в запросе присутствуют поля паспорта студента или поля сотрудника."""
    fullName: String!
    """Роль. Использовать только если в запросе присутствует student или employee.isAdmin."""
    role: UserRoleEnum!
}

extend type StudentEntity {
    """Инициалы. Использовать только если в запросе присутствует паспорт студента."""
    initials: String!
    """Полное имя. Использовать только если в запросе присутствует паспорт студента."""
    fullName: String!
}

extend type EmployeeEntity {
    """Инициалы"""
    initials: String!
    """Полное имя"""
    fullName: String!
}
