directive @client on FIELD

#################################################################################
# Файл используется при фетчинге схемы бэкенда и объединяется с основной схемой #
#################################################################################

extend type UserEntity {
    """Инициалы. Использовать только если в запросе присутствует паспорт студента или поля сотрудника"""
    initials: String!
    """Полное имя. Использовать только если в запросе присутствует паспорт студента или поля сотрудника"""
    fullName: String!
    """Роль. Использовать только если в запросе присутствует student или employee.isAdmin"""
    role: UserRoleEnum!
}

extend type StudentEntity {
    """Инициалы"""
    initials: String!
    """Полное имя"""
    fullName: String!
}

extend type EmployeeEntity {
    """Инициалы"""
    initials: String!
    """Полное имя"""
    fullName: String!
}
